"""Command-line entry point for ssh-starter."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

from app.config import AppConfig, default_config_path
from app.history import ConnectionHistory, default_history_path
from app.models import SshRunResult
from app.ssh_config import load_inventory
from app.ui import SessionEndedApp, SshLauncherApp

OPENSSH_DEFAULT_CONFIG = Path("~/.ssh/config")
SAMPLE_SSH_CONFIG = """# Sample profile generated by ssh-starter.
# Edit HostName, User, Port, and IdentityFile values for your server.
Host sample-server
    HostName 192.0.2.10
    User deploy
    Port 22
"""


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Full-screen SSH profile launcher.")
    parser.add_argument(
        "--app-config",
        type=Path,
        default=None,
        help=f"Path to ssh-starter config.toml. Defaults to {default_config_path()}.",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=None,
        help="Path to OpenSSH config. Overrides config.toml ssh_config_path.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the ssh command after selection instead of executing it.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    app_config_path = (args.app_config or default_config_path()).expanduser()

    try:
        app_config = _load_app_config(app_config_path, create_missing=args.app_config is None)
    except (FileNotFoundError, OSError, ValueError) as exc:
        print(f"ssh-starter config error: {exc}", file=sys.stderr)
        return 2

    ssh_config_path = (args.config or app_config.expanded_ssh_config_path()).expanduser()
    preflight_exit_code = _preflight_ssh_config(ssh_config_path)
    if preflight_exit_code is not None:
        return preflight_exit_code

    history_path = default_history_path()
    history = ConnectionHistory.load(history_path)

    while True:
        inventory = load_inventory(ssh_config_path)
        app = SshLauncherApp(inventory, app_config, app_config_path, history)
        app.run()
        app_config = app.app_config
        history = app.history

        if app.selected_alias is None:
            return 0

        command = _ssh_command(app.selected_alias, ssh_config_path)
        if args.dry_run:
            print(" ".join(command))
            return 0

        history = history.mark_connected(app.selected_alias)
        try:
            history.save(history_path)
        except OSError as exc:
            print(f"ssh-starter history error: could not save connection history: {exc}", file=sys.stderr)

        result = _run_ssh(app.selected_alias, command, app_config.term_string)
        SessionEndedApp(result).run()


def _load_app_config(config_path: Path, *, create_missing: bool) -> AppConfig:
    """Load app config, creating the default user config only for implicit first run."""
    if config_path.exists():
        return AppConfig.load(config_path)
    if not create_missing:
        return AppConfig.load(config_path)

    app_config = AppConfig.create_default(config_path)
    print(f"Created default ssh-starter config: {config_path}", file=sys.stderr)
    return app_config


def _run_ssh(alias: str, command: list[str], term_string: str) -> SshRunResult:
    ssh_env = os.environ.copy()
    ssh_env["TERM"] = term_string

    try:
        completed = subprocess.run(command, check=False, env=ssh_env)
    except FileNotFoundError:
        return SshRunResult(
            alias=alias,
            command=tuple(command),
            exit_code=127,
            term_string=term_string,
            error_message="ssh command not found in PATH.",
        )
    except KeyboardInterrupt:
        return SshRunResult(
            alias=alias,
            command=tuple(command),
            exit_code=130,
            term_string=term_string,
            error_message="ssh session was interrupted.",
        )
    return SshRunResult(
        alias=alias,
        command=tuple(command),
        exit_code=completed.returncode,
        term_string=term_string,
    )


def _preflight_ssh_config(config_path: Path) -> int | None:
    """Validate OpenSSH config before starting the full-screen UI."""
    expanded_path = config_path.expanduser()
    if not expanded_path.exists():
        print(f"ssh-starter error: OpenSSH config not found: {expanded_path}", file=sys.stderr)
        return 2
    if not expanded_path.is_file():
        print(f"ssh-starter error: OpenSSH config is not a regular file: {expanded_path}", file=sys.stderr)
        return 2
    if not _ssh_config_has_content(expanded_path):
        print(f"ssh-starter error: OpenSSH config is empty: {expanded_path}", file=sys.stderr)
        if _confirm_sample_config_creation(expanded_path):
            try:
                _create_sample_ssh_config(expanded_path)
            except OSError as exc:
                print(f"ssh-starter error: could not create sample SSH config: {exc}", file=sys.stderr)
                return 2
            print(f"Sample SSH profile created in {expanded_path}.")
            print("Edit it for your server, then run ssh-starter again.")
            return 0
        print("No SSH profiles were created. Edit your SSH config, then run ssh-starter again.")
        return 2
    return None


def _ssh_config_has_content(config_path: Path) -> bool:
    """Return True when config has at least one non-comment, non-empty line."""
    with config_path.open("r", encoding="utf-8") as config_file:
        for raw_line in config_file:
            stripped = raw_line.strip()
            if stripped and not stripped.startswith("#"):
                return True
    return False


def _confirm_sample_config_creation(config_path: Path) -> bool:
    """Ask whether to create a sample profile when the config file is empty."""
    if not sys.stdin.isatty():
        return False
    answer = input(f"Create a sample SSH profile in {config_path}? [y/N] ").strip().lower()
    return answer in {"y", "yes"}


def _create_sample_ssh_config(config_path: Path) -> None:
    """Write the sample profile into an existing empty or comment-only config file."""
    config_path.parent.mkdir(parents=True, exist_ok=True)
    existing_text = config_path.read_text(encoding="utf-8") if config_path.exists() else ""
    separator = "\n\n" if existing_text.strip() else ""
    config_path.write_text(
        f"{existing_text.rstrip()}{separator}{SAMPLE_SSH_CONFIG}",
        encoding="utf-8",
    )


def _ssh_command(alias: str, selected_config: Path) -> list[str]:
    selected_config = selected_config.expanduser().resolve()
    default_config = OPENSSH_DEFAULT_CONFIG.expanduser().resolve()
    if selected_config == default_config:
        return ["ssh", alias]
    return ["ssh", "-F", str(selected_config), alias]


if __name__ == "__main__":
    raise SystemExit(main())
